### ISSUE TITLE
Can this library keep at least the tab title?

### ISSUE THREAD

**Issue by mcxinyu** [michael-rapp/ChromeLikeTabSwitcher#15]
Can this library keep at least the tab title?

**Comment by michael-rapp** [comment]
Could you please explain what exactly your issue is?

**Comment by mcxinyu** [comment]
When the tabs slide up and down, I want to keep the tab's title displayed, not blocked by other tabs.

**Comment by michael-rapp** [comment]
I see...but this is not how the Chrome app behaves and as this library is meant to mimic its behavior such a feature is not implemented. Of course it would be possible with some modifications, but I guess this will cause some practical issues. For example, imagine a scenario with a lot of tabs. When scrolling through them they will be stacked at the top (or bottom) causing less space to be available for displaying the remaining (moving) tabs. If enough tabs are stacked no space will be left at all.

**Comment by mcxinyu** [comment]
Can you use it as an optional feature?

![tim 20180413085641](https://user-images.githubusercontent.com/9566116/38711592-2c380236-3ef9-11e8-9e03-1071486b4e45.jpg)
![tim 20180413085702](https://user-images.githubusercontent.com/9566116/38711593-2c69e72e-3ef9-11e8-9d64-e1a15b7f50ec.jpg)

**Comment by michael-rapp** [comment]
Ok, the image you have posted suggests that the tabs are positioned differently in relation to each other when compared to the Chrome app. This enables to display the titles of a few tabs while the remaining ones still become invisible when scrolling far enough, which prevents the problems I described above.

The problem is, that the code for positioning the tabs is quite complicated and I don't have the resources and time to maintain two implementations of the scrolling behavior. For this reason I unfortunately must reject your feature request.
