### ISSUE TITLE
Click event is not happening everytime

### ISSUE THREAD

**Issue by milek** [michael-rapp/ChromeLikeTabSwitcher#2]
After opening switcher, and dragging tabs around, clickEvent is not being triggered.
As a temporary fix, I've changed following lines inside AbstractDragHandler method handleRelease()

```java
        } else if (dragState == DragState.NONE || (event != null && !dragHelper.hasThresholdBeenReached() &&
                !swipeDragHelper.hasThresholdBeenReached())) {
            handleClick(event);
        }
```

I'm just not sure if this doesn't break anything... As far as it goes, nothing has been broken
Tested on both 0.1.0 and 1.0.0 branches.

**Comment by michael-rapp** [comment]
Thank you for your suggestion. When testing your change I did not encounter any regressions either. However, the `if`-clause can be simplified. The condition `dragState == DragState.NONE` is always true, because all other states of that variable are already covered by the preceding `if`-clauses. Therefore the condition after the `||` operator is never tested and can be omitted. In return, the condition `event != null` should be included to avoid NPEs. In conclusion, I changed the code to the following:

```java
        } else if (event != null) {
            handleClick(event);
        }
```

The change is included in the 0.1.1 bugfix release.
