### ISSUE TITLE
No methods in bundle for states

### ISSUE THREAD

**Issue by emrekanca** [michael-rapp/ChromeLikeTabSwitcher#27]
What am I doing wrong?

![image](https://user-images.githubusercontent.com/1078420/82186193-23018b00-98f3-11ea-9684-4f0cbfad66a2.png)

state.saveInstanceState
state.loadItems
state.restoreInstanceState

cannot be resolved

**Comment by michael-rapp** [comment]
As the code you have posted is not complete, it is not possible to reason about what the actual problem is.

However, in the class [`MainActivity`](https://github.com/michael-rapp/ChromeLikeTabSwitcher/blob/master/example/src/main/java/de/mrapp/android/tabswitcher/example/MainActivity.java) of the example app you can find a similar piece of code. It is necessary that the class `State` extends from the class [`AbstractState`](https://github.com/michael-rapp/ChromeLikeTabSwitcher/blob/master/library/src/main/java/de/mrapp/android/tabswitcher/AbstractState.java) and properly implements the method `saveInstanceState`. Please make sure that you have such a class in your code and that `State` actually refers to this class.
